name: Flutter CI + CD

on:
  push: 
    branches: [ main ]  
  pull_request:
    branches: [ main ]  
  workflow_dispatch:   

env:
  FLUTTER_CHANNEL: 'stable'        
  FLUTTER_VERSION: '3.22.2'          
  PATH_TO_AAB: 'build/app/outputs/bundle/release/app-release.aab'  
  ANDROID_PACKAGE_NAME: 'com.vibehunt.com' 

jobs:
  # Job 1: Code Analysis and Testing
  code-analysis-and-testing:
    name: Code Analysis and Testing
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        shell: bash

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        run: flutter pub get --verbose

      - name: Run Flutter analyze
        run: flutter analyze  

      - name: Run Flutter tests
        run: flutter test